apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: global-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    mode: standalone
    highAvailabilityCIS:
      primaryCluster:
        clusterName: kubernetes-1-27
        secret: default/kubernetes-1-27
    externalClustersConfig:
    - clusterName: kubernetes-1-28
      secret: default/kubernetes-1-28