apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: edge-tls
  namespace: cafeone
spec:
  hosts:
    - cafe.example.com
  tls:
  termination: edge
    clientSSLs:
      - /Common/clientssl
    termination: bigip