apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: vs-coffee-ab
  namespace: cafeone
spec:
  virtualServerAddress: 10.192.75.121
  host: cafe.example.com
  pools:
    - path: /coffee
      service: coffee-svc
      servicePort: 8080
      weight: 70
      alternateBackends:
        - service: coffee-svc
          weight: 30
          serviceNamespace: cafetwo