apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: vs-hello-ab
  namespace: default
spec:
  host: cafe.example.com
  pools:
    - path: /
      service: hello-world-app-a
      servicePort: 8080
      weight: 70
      alternateBackends:
        - service: hello-world-app-b
          weight: 30
          serviceNamespace: default
  virtualServerAddress: 10.192.75.121